#!/usr/bin/env bash
set -Eeuo pipefail

# Build a Debian Trixie unattended-install ISO with:
#    - one Ed25519 laptop/client authentication key;
#    - the client's PUBLIC key installed in root and admin authorized_keys;
#    - unique SSH server host keys generated by Debian on the installed machine;
#    - hybrid post-quantum SSH key exchange configured before first boot;
#    - age, OpenSSH, UFW, curl, wget, and git installed;
#    - largest detected disk selected for automatic partitioning.
#
# The private client key is kept outside the ISO.
# No reusable server host private key is placed in the ISO.
#
# Required:
	imagepassword='testImage'
	ROOT_PASSWORD_HASH=$(printf '%s\n' "$imagepassword-root" | openssl passwd -6 -stdin)
	ADMIN_PASSWORD_HASH=$(printf '%s\n' "$imagepassword-user" | openssl passwd -6 -stdin)
	export ROOT_PASSWORD_HASH
	export ADMIN_PASSWORD_HASH
#
# Run:
#	bash CUSTtrixieISOmaker.sh
#
# Before writing the resulting ISO to USB, review this script and the generated
# preseed.cfg carefully. Automatic partitioning erases the selected largest disk.

[[ "${EUID}" -eq 0 ]] || {
    echo "Run as root: sudo -E $0" >&2
    exit 1
}

: "${ROOT_PASSWORD_HASH:?Set ROOT_PASSWORD_HASH first}"
: "${ADMIN_PASSWORD_HASH:?Set ADMIN_PASSWORD_HASH first}"

# ----------------------------- Configuration -----------------------------

WORK_DIR="${WORK_DIR:-/home/$USER/debian-iso-builder}"
KEY_DIR="$WORK_DIR/keys"
ISO_DIR="$WORK_DIR/iso"
MOUNT_DIR="$WORK_DIR/mnt"
PRESEED="$WORK_DIR/preseed.cfg"
OUTPUT_ISO="${OUTPUT_ISO:-$WORK_DIR/custom-deb.iso}"
DOWNLOADED_ISO="$WORK_DIR/debian-base.iso"

ADMIN_USER="yousir"
ADMIN_FULLNAME="Yousir WEIFS"

HYBRID_KEX="mlkem768x25519-sha256,sntrup761x25519-sha512,curve25519-sha256"

WIFI_SSID="${WIFI_SSID:-mycorrectSSID}"
WIFI_PASSWORD="${WIFI_PASSWORD:-mycorrectSSIDpassword}"

# ----------------------------- Cleanup -----------------------------

cleanup() {
    set +e
    mountpoint -q "$MOUNT_DIR" && umount "$MOUNT_DIR"
}
trap cleanup EXIT

rm -rf "$WORK_DIR"
mkdir -p "$KEY_DIR" "$ISO_DIR" "$MOUNT_DIR"
chmod 777 "$WORK_DIR"
chmod 700 "$KEY_DIR"

# ----------------------------- Client key only -----------------------------
# all the "" variables can be configured at your will / preferences.
ssh-keygen -q -t ed25519 \
    -C "authLptpLocalCLient" \
    -f "$KEY_DIR/authLptpLocalCLient" \
    -N "" 
#type a key-acceess password in the "" above if you want.

chmod 600 "$KEY_DIR/authLptpLocalCLient"
chmod 644 "$KEY_DIR/authLptpLocalCLient.pub"

ssh-keygen -lf "$KEY_DIR/authLptpLocalCLient.pub" >/dev/null

CLIENT_PUBLIC_KEY="$(cat "$KEY_DIR/authLptpLocalCLient.pub")"

# ----------------------------- Create preseed -----------------------------

cat > "$PRESEED" <<EOF
### Debian Trixie unattended installation

# ---------------- Localization ----------------

d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us
d-i time/zone string America/New_York
d-i clock-setup/utc boolean true
d-i clock-setup/ntp boolean true

# ---------------- Network ----------------

d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string DEBIANcustom
d-i netcfg/get_domain string

d-i netcfg/wireless_essid string ${WIFI_SSID}
d-i netcfg/wireless_security_type select wpa
d-i netcfg/wireless_wpa string ${WIFI_PASSWORD}
d-i netcfg/link_detect_timeout string 5

d-i netcfg/no_default_route boolean true

# ---------------- Debian mirror ----------------

d-i mirror/country string manual
d-i mirror/http/hostname string merlin.fit.vutbr.cz
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string
d-i apt-setup/use_mirror boolean false

# ---------------- Accounts ----------------

d-i passwd/root-login boolean true
d-i passwd/root-password-crypted password ${ROOT_PASSWORD_HASH}

d-i passwd/user-fullname string ${ADMIN_FULLNAME}
d-i passwd/username string ${ADMIN_USER}
d-i passwd/user-password-crypted password ${ADMIN_PASSWORD_HASH}
d-i passwd/user-default-groups string audio cdrom video sudo

# ---------------- Partitioning ----------------

d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nochanges boolean true
d-i partman-md/confirm boolean true
d-i partman-lvm/confirm boolean true

d-i partman/early_command string \\
    disk="\$(for d in \$(list-devices disk); do printf '%s %s\\n' "\$(blockdev --getsize64 "\$d")" "\$d"; done | sort -nr | awk 'NR==1 {print \$2}'); \\
    [ -n "\$disk" ] || exit 1; \\
    debconf-set partman-auto/disk "\$disk"

# ---------------- Packages ----------------

tasksel tasksel/first multiselect standard, ssh-server, web-server
d-i pkgsel/include string openssh-server age ufw curl wget git ca-certificates openssh-server tor apt-transport-tor torsocks
d-i pkgsel/upgrade select none
d-i pkgsel/update-policy select none

# ---------------- Bootloader ----------------

d-i grub-installer/only_debian boolean true
d-i grub-installer/bootdev string default

# ---------------- Pre-first-boot configuration ----------------

d-i preseed/late_command string \\
    in-target install -d -m 755 /etc/ssh/sshd_config.d; \\
    in-target install -d -m 755 /etc/ssh/ssh_config.d; \\
    in-target sh -c 'printf "%s\\n" "KexAlgorithms ${HYBRID_KEX}" > /etc/ssh/sshd_config.d/20-hybrid-kex.conf'; \\
    in-target sh -c 'printf "%s\\n" "KexAlgorithms ${HYBRID_KEX}" > /etc/ssh/ssh_config.d/20-hybrid-kex.conf'; \\
    in-target sshd -t; \\
    in-target install -d -m 700 /root/.ssh; \\
    printf '%s\\n' '${CLIENT_PUBLIC_KEY}' > /target/root/.ssh/authorized_keys; \\
    in-target chown root:root /root/.ssh /root/.ssh/authorized_keys; \\
    in-target chmod 700 /root/.ssh; \\
    in-target chmod 600 /root/.ssh/authorized_keys; \\
    in-target install -d -m 700 /home/${ADMIN_USER}/.ssh; \\
    printf '%s\\n' '${CLIENT_PUBLIC_KEY}' > /target/home/${ADMIN_USER}/.ssh/authorized_keys; \\
    in-target chown -R ${ADMIN_USER}:${ADMIN_USER} /home/${ADMIN_USER}/.ssh; \\
    in-target chmod 700 /home/${ADMIN_USER}/.ssh; \\
    in-target chmod 600 /home/${ADMIN_USER}/.ssh/authorized_keys; \\
    in-target ufw default deny incoming; \\
    in-target ufw default allow outgoing; \\
    in-target ufw allow ssh; \\
    in-target ufw allow http; \\
    in-target ufw --force enable; \\
    in-target systemctl enable ssh; \\
    in-target sh -c 'cat > /etc/apt/sources.list.d/debian-tor.sources <<APT
Types: deb
URIs: tor+https://merlin.fit.vutbr.cz/debian
Suites: trixie trixie-updates
Components: main contrib non-free non-free-firmware
Architectures: amd64
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: tor+https://merlin.fit.vutbr.cz/debian-security
Suites: trixie-security
Components: main contrib non-free non-free-firmware
Architectures: amd64
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
APT'; \\
    in-target rm -f /etc/apt/sources.list; \\
    in-target systemctl enable tor


EOF

chmod 600 "$PRESEED"

# ----------------------------- Download ISO -----------------------------

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates \
    curl \
    xorriso \
    isolinux \
    syslinux-common

# this is only an example for your ISO images directory.
LOCAL_ISO_DIR="/home/$USER/DEVELOPPMENT/debianwebsiteimages/DVD1deb64"

LOCAL_ISO="$(
    find "$LOCAL_ISO_DIR" \
        -maxdepth 1 \
        -type f \
        -iname '*amd64*DVD*1*.iso' \
        -print \
        -quit
)"

[[ -n "$LOCAL_ISO" ]] || {
    echo "No Debian AMD64 DVD-1 ISO found in:" >&2
    echo "  $LOCAL_ISO_DIR" >&2
    exit 1
}

echo "Using local ISO:"
echo "  $LOCAL_ISO"

cp -- "$LOCAL_ISO" "$DOWNLOADED_ISO"

[[ -s "$DOWNLOADED_ISO" ]] || {
    echo "Failed to copy the ISO to:" >&2
    echo "  $DOWNLOADED_ISO" >&2
    exit 1
}

echo "ISO copied to:"
echo "  $DOWNLOADED_ISO"

# ----------------------------- Extract ISO -----------------------------

mount -o loop,ro "$DOWNLOADED_ISO" "$MOUNT_DIR"
cp -a "$MOUNT_DIR"/. "$ISO_DIR"/
umount "$MOUNT_DIR"

chmod -R u+w "$ISO_DIR"
cp "$PRESEED" "$ISO_DIR/preseed.cfg"

# ----------------------------- Add boot entries -----------------------------

if [[ -f "$ISO_DIR/boot/grub/grub.cfg" ]]; then
    cat > "$ISO_DIR/boot/grub/grub.cfg" <<'GRUB'
set default=0
set timeout=0
set timeout_style=hidden

menuentry "Automated Install (Preseed)" {
    set background_color=black
    linux /install.amd/vmlinuz auto=true priority=critical preseed/file=/cdrom/preseed.cfg --- quiet
    initrd /install.amd/initrd.gz
}
GRUB
fi

if [[ -f "$ISO_DIR/isolinux/txt.cfg" ]]; then
    cat > "$ISO_DIR/isolinux/txt.cfg" <<'ISOLINUX'
default auto-preseed
label auto-preseed
    menu label Automated Install (Preseed)
    kernel /install.amd/vmlinuz
    append auto=true priority=critical preseed/file=/cdrom/preseed.cfg initrd=/install.amd/initrd.gz --- quiet
ISOLINUX
fi

if [[ -f "$ISO_DIR/isolinux/isolinux.cfg" ]]; then
    cat > "$ISO_DIR/isolinux/isolinux.cfg" <<'ISOLINUX'
default auto-preseed
prompt 0
timeout 0
ontimeout auto-preseed
include txt.cfg
ISOLINUX
fi

# ----------------------------- Rebuild hybrid BIOS/UEFI ISO -----------------------------

cp /usr/lib/ISOLINUX/isohdpfx.bin "$ISO_DIR/isolinux/isohdpfx.bin"
chmod 600 "$ISO_DIR/isolinux/isohdpfx.bin"

xorriso -as mkisofs \
    -r \
    -V "DEBIANCUSTOM" \
    -o "$OUTPUT_ISO" \
    -isohybrid-mbr "$ISO_DIR/isolinux/isohdpfx.bin" \
    -c isolinux/isolinux.cat \
    -b isolinux/isolinux.bin \
    -no-emul-boot \
    -boot-load-size 4 \
    -boot-info-table \
    -eltorito-alt-boot \
    -e boot/grub/efi.img \
    -no-emul-boot \
    -isohybrid-gpt-basdat \
    "$ISO_DIR"

chmod 644 "$OUTPUT_ISO"

# ----------------------------- Results -----------------------------

echo
echo "Build complete."
echo
echo "ISO:"
echo "  $OUTPUT_ISO"
echo
echo "Keep this private on the laptop/client:"
echo "  $KEY_DIR/authLptpLocalCLient"
echo
echo "The public key embedded in the installed server is:"
echo "  $KEY_DIR/authLptpLocalCLient.pub"
echo
echo "No server host private key was embedded in the ISO."
echo "The installed server will generate unique SSH host keys."
echo
echo "Hybrid SSH KEX configured before first boot:"
echo "  $HYBRID_KEX"
echo
echo "Write the ISO only after review:"
echo "  sudo dd if='$OUTPUT_ISO' of=/dev/sdX bs=4M status=progress oflag=sync"
echo
echo "After installation, verify supported KEX algorithms:"
echo "  ssh -Q kex | grep -E 'mlkem|sntrup'"
echo
echo "Verify the negotiated algorithm from the client:"
echo "  ssh -vv root@SERVER 2>&1 | grep -i 'kex'"

cp -fs \
    /home/$USER/debian-iso-builder-VERSION_2.0.0/CUSTtrixieISOmaker.sh \
    /home/$USER/debian-iso-builder

rm -R /home/$USER/debian-iso-builder/iso
ls /home/$USER/debian-iso-builder/keys
rm -R /home/$USER/debian-iso-builder/mnt
rm /home/$USER/debian-iso-builder/preseed.cfg
rm /home/$USER/debian-iso-builder/debian-base.iso

chmod 777 /home/$USER/debian-iso-builder/custom-deb.iso

if [[ -f "/home/$USER/debian-iso-builder/$(basename "/home/$USER/debian-iso-builder-VERSION_2.0.0/CUSTtrixieISOmaker.sh")" ]]; then
    cp -f \
        "/home/$USER/debian-iso-builder-VERSION_2.0.0/CUSTtrixieISOmaker.sh" \
        "/home/$USER/debian-iso-builder/"
fi
